### ISSUE TITLE
PiP (Picture in Picture) Mode 

### ISSUE THREAD

**Issue by Skullhunter11** [anilbeesetti/nextplayer#573] opened 2023-09-06 08:47 UTC
For when people like me want to watch a video while scrolling

**Comment by VasilisKos** [comment] 2023-09-06 10:01
Please, READ THE DESCRIPTION before posting:

"Planned Features:
External Audio support
**Picture-in-picture mode**"

**Comment by Pentaphon** [comment] 2023-09-30 11:00
Dupe of https://github.com/anilbeesetti/nextplayer/issues/250

**Comment by walrus543** [comment] 2024-01-03 16:23
@Skullhunter11 please close this issue.

**Comment by anilbeesetti** [comment] 2024-02-12 04:21
- feature added in PR #646

**Closed as completed by anilbeesetti** 2024-02-12 04:21 UTC
